name: Build Windows App and Installer

on:
  push:
    tags:
      - 'v*'
      - '*.*.*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r build/requirements-alpha.txt

      - name: Build app (onedir + onefile)
        shell: cmd
        run: build\win_build_release.bat

      - name: Install Inno Setup (for ISCC)
        shell: powershell
        run: choco install innosetup -y --no-progress

      - name: Build installer
        shell: cmd
        run: build\run_iscc.bat

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            dist/eF Drift Car Scrutineer.exe
            dist/efdrift-scrutineer-setup-*.exe
            dist/eF Drift Car Scrutineer/**

      - name: Attach to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/eF Drift Car Scrutineer.exe
            dist/efdrift-scrutineer-setup-*.exe
